### ISSUE TITLE
version of python

### ISSUE THREAD

**Issue by vvincenttttt** [AllentDan/SegmentationCpp#4]
Hi, 
Thanks for your code.

Could you include your code impllemented by python ?
Thanks!

**Comment by AllentDan** [comment]
Hi, @TianhaoFu, thanks for your issue.

The project is purely based on C++. Only the backbone weights generation needs pytorch. The pytorch version is 1.7- and python version is 3.5+. You can check the [SMP](https://github.com/qubvel/segmentation_models.pytorch) project if you want to train models in python. 

BTW, this project cannot ensure you can load the weights trained by SMP into C++ because some operations or layer names are not same.
